package main

import "math/rand"

type stratagem struct {
	name string
	code []rune
}

var STRATAGEMS = []stratagem{
	{"LIFT-850 Jump Pack", []rune{'d', 'u', 'u', 'd', 'u'}},
	{"B-1 Supply Pack", []rune{'d', 'l', 'd', 'u', 'u', 'd'}},
	{"SH-20 Ballistic Shield Backpack", []rune{'d', 'l', 'd', 'd', 'u', 'l'}},
	{"SH-51 Directional Shield Backpack", []rune{'d', 'u', 'l', 'r', 'u', 'u'}},
	{"SH-32 Shield Generator Pack", []rune{'d', 'u', 'l', 'r', 'l', 'r'}},
	{"AX/AR-23 Guard Dog", []rune{'d', 'u', 'l', 'u', 'r', 'd'}},
	{"AX/LAS-5 Guard Dog Rover", []rune{'d', 'u', 'l', 'u', 'r', 'r'}},
	{"AX/TX-13 Guard Dog Dog Breath", []rune{'d', 'u', 'l', 'u', 'r', 'u'}},
	{"MG-43 Machine Gun", []rune{'d', 'l', 'd', 'u', 'r'}},
	{"APW-1 Anti-Materiel Rifle", []rune{'d', 'l', 'r', 'u', 'd'}},
	{"M-105 Stalwart", []rune{'d', 'l', 'd', 'u', 'u', 'l'}},
	{"EAT-17 Expendable Anti-tank", []rune{'d', 'd', 'l', 'u', 'r'}},
	{"MLS-4X Commando", []rune{'d', 'l', 'u', 'd', 'r'}},
	{"GR-8 Recoilless Rifle", []rune{'d', 'l', 'r', 'r', 'l'}},
	{"FLAM-40 Flamethrower", []rune{'d', 'l', 'u', 'd', 'u'}},
	{"AC-8 Autocannon", []rune{'d', 'l', 'd', 'u', 'u', 'r'}},
	{"MG-206 Heavy Machine Gun", []rune{'d', 'l', 'u', 'd', 'd'}},
	{"RS-422 Railgun", []rune{'d', 'r', 'd', 'u', 'l', 'r'}},
	{"FAF-14 Spear Launcher", []rune{'d', 'd', 'u', 'd', 'd'}},
	{"GL-21 Grenade Launcher", []rune{'d', 'l', 'u', 'l', 'd'}},
	{"LAS-98 Laser Cannon", []rune{'d', 'l', 'd', 'u', 'l'}},
	{"ARC-3 Arc Thrower", []rune{'d', 'r', 'd', 'u', 'l', 'l'}},
	{"LAS-99 Quasar Cannon", []rune{'d', 'd', 'u', 'l', 'r'}},
	{"RL-77 Airburst Rocket Launcher", []rune{'d', 'u', 'u', 'l', 'r'}},
	{"TX-14 Sterilizer", []rune{'d', 'l', 'u', 'd', 'l'}},
	{"StA-X3_W.A.S.P. Launcher", []rune{'d', 'd', 'u', 'd', 'r'}},
	{"EXO-45 Patriot Exosuit", []rune{'l', 'd', 'r', 'u', 'l', 'd', 'd'}},
	{"EXO-49 Emancipator Exosuit", []rune{'l', 'd', 'r', 'u', 'l', 'd', 'u'}},
	{"M-102 Fast Recon Vehicle", []rune{'l', 'd', 'r', 'd', 'r', 'd', 'u'}},
	{"Reinforce", []rune{'u', 'd', 'r', 'l', 'u'}},
	{"SOS Beacon", []rune{'u', 'd', 'r', 'u'}},
	{"Resupply", []rune{'d', 'd', 'u', 'r'}},
	{"NUX-223 Hellbomb", []rune{'d', 'u', 'l', 'd', 'u', 'r', 'd', 'u'}},
	{"SSSD Delivery", []rune{'d', 'd', 'd', 'u', 'u'}},
	{"Seismic Probe", []rune{'u', 'u', 'l', 'r', 'd', 'd'}},
	{"Upload Data", []rune{'l', 'r', 'u', 'u', 'u'}},
	{"Eagle Rearm", []rune{'u', 'u', 'l', 'u', 'r'}},
	{"SEAF Artillery", []rune{'r', 'u', 'u', 'd'}},
	{"Super Earth Flag", []rune{'d', 'u', 'd', 'u'}},
	{"Hive Breaker Drill", []rune{'l', 'u', 'd', 'r', 'd', 'd'}},
	{"E/MG-101 HMG Emplacement", []rune{'d', 'u', 'l', 'r', 'r', 'l'}},
	{"E/AT-12 Anti-Tank Emplacement", []rune{'l', 'l', 'u', 'u', 'r', 'l'}},
	{"FX-12 Shield Generator Relay", []rune{'d', 'd', 'l', 'r', 'l', 'r'}},
	{"A/ARC-3 Tesla Tower", []rune{'d', 'u', 'r', 'u', 'l', 'r'}},
	{"MD-6 Anti-Personnel Minefield", []rune{'d', 'l', 'u', 'r'}},
	{"MD-I4 Incendiary Mines", []rune{'d', 'l', 'l', 'd'}},
	{"MD-17 Anti-Tank Mines", []rune{'d', 'l', 'u', 'u'}},
	{"A/MG-43 Machine Gun Sentry", []rune{'d', 'u', 'r', 'r', 'u'}},
	{"A/G-16 Gatling Sentry", []rune{'d', 'u', 'r', 'l'}},
	{"A/M-12 Mortar Sentry", []rune{'d', 'u', 'r', 'r', 'd'}},
	{"A/AC-8 Autocannon Sentry", []rune{'d', 'u', 'r', 'u', 'l', 'u'}},
	{"A/MLS-4X Rocket Sentry", []rune{'d', 'u', 'r', 'r', 'l'}},
	{"A/M-23 EMS Mortar Sentry", []rune{'d', 'u', 'r', 'd', 'r'}},
	{"E/FLAM-40 Flame Sentry", []rune{'d', 'u', 'r', 'd', 'u', 'u'}},
	{"Orbital Gatling Barrage", []rune{'r', 'd', 'l', 'u', 'u'}},
	{"Orbital Airburst Strike", []rune{'r', 'r', 'r'}},
	{"Orbital 120MM HE Barrage", []rune{'r', 'r', 'd', 'l', 'r', 'd'}},
	{"Orbital 380MM HE Barrage", []rune{'r', 'd', 'u', 'u', 'l', 'd', 'd'}},
	{"Orbital Walking Barrage", []rune{'r', 'd', 'r', 'd', 'r', 'd'}},
	{"Orbital Laser", []rune{'r', 'd', 'u', 'r', 'd'}},
	{"Orbital Railcannon Strike", []rune{'r', 'u', 'd', 'd', 'r'}},
	{"Orbital Precision Strike", []rune{'r', 'r', 'u'}},
	{"Orbital Gas Strike", []rune{'r', 'r', 'd', 'r'}},
	{"Orbital EMS Strike", []rune{'r', 'r', 'l', 'd'}},
	{"Orbital Smoke Strike", []rune{'r', 'r', 'd', 'u'}},
	{"Orbital Napalm Barrage", []rune{'r', 'r', 'd', 'l', 'r', 'u'}},
	{"Eagle Strafing Run", []rune{'u', 'r', 'r'}},
	{"Eagle Airstrike", []rune{'u', 'r', 'd', 'r'}},
	{"Eagle Cluster Bomb", []rune{'u', 'r', 'd', 'd', 'r'}},
	{"Eagle Napalm Airstrike", []rune{'u', 'r', 'd', 'u'}},
	{"Eagle Smoke Strike", []rune{'u', 'r', 'u', 'd'}},
	{"Eagle 110MM Rocket Pods", []rune{'u', 'r', 'u', 'l'}},
	{"Eagle 500kg Bomb", []rune{'u', 'r', 'd', 'd', 'd'}},
}

func GetRandomStratagem() stratagem {
	randomIndex := rand.Intn(len(STRATAGEMS))
	return STRATAGEMS[randomIndex]
}
